name: refilc_kreta_api
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  refilc:
    path: ../refilc/
  http: ^0.13.3
  provider: ^5.0.0
  file_picker: ^5.3.2

dev_dependencies:
  flutter_lints: ^1.0.0
